apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-use
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /produse
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
